databaseChangeLog:
  - changeSet:
      id: 2
      author: quinn
      changes:
        - createTable:
            tableName: products
            columns:
              - column:
                  name: product_id
                  type: SERIAL
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(100)
                  constraints:
                    nullable: false
              - column:
                  name: category
                  type: VARCHAR(100)
                  constraints:
                    nullable: false
              - column:
                  name: price
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: seller_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: TEXT
              - column:
                  name: image_url
                  type: VARCHAR(100)
                  constraints:
                    nullable: true

  - changeSet:
      id: 3
      author: quinn
      changes:
        - addForeignKeyConstraint:
            baseTableName: products
            baseColumnNames: seller_id
            referencedTableName: user
            referencedColumnNames: user_id
            constraintName: fk_product_seller
            deferrable: false
            initiallyDeferred: false
            onDelete: CASCADE